 INSERT INTO Producto (nombre, categoria, descripcion, precio, src_imagen, tamanio) VALUES

	('Shampoo de coco 80 gr', 'Shampoo sólido', 'El shampoo de coco sólido está diseñado para cabello normal o mixto y es elaborado con aceite de coco, aceite de oliva y vitamina E. Estos ingredientes proporcionan una limpieza suave pero efectiva al cabello, al mismo tiempo que lo hidratan y lo protegen.', 120, 'CocoTiendaBC.jpg', '80 gr'),
    ('Shampoo de carbón activado 80gr', 'Shampoo sólido', 'El shampoo sólido de carbón activado con aceite de ricino, aceite de coco, carbón activado y romero es una fórmula innovadora que combina los beneficios de varios ingredientes naturales para proporcionar una limpieza profunda y efectiva al cabello normal o mixto.', 120, 'CarbonTiendaBC.jpg', '80 gr'),
    ('Shampoo de chocoalmendras 80 gr', 'Shampoo sólido', 'El shampoo de chocoalmendras es una opción para combatir el cabello seco y para evitar el frizz en cabello. Este shampoo está elaborado con manteca de cacao, aceite de almendras y vitamina E, tres ingredientes naturales que proporcionan una hidratación profunda al cabello, al mismo tiempo que lo nutren y protegen de los efectos dañinos del medio ambiente y los procesos químicos.', 120, 'ChocoAlmTiendaBC.jpg', '80 gr'),
    ('Shampoo de trigo 80 gr','Shampoo sólido','El shampoo sólido de trigo para cabello seco es una opción natural y efectiva para hidratar y nutrir el cabello seco. Este shampoo sólido está elaborado con aceite de trigo y vitamina E, dos ingredientes que proporcionan una hidratación profunda al cabello, ayudando a restaurar su suavidad y brillo natural.',120,'FibraTiendaBC.jpg','80 gr'),
    ('Shampoo de aguacate 80 gr', 'Shampoo sólido', 'El shampoo sólido de aguacate es un producto de cuidado capilar natural y ecológico que ha ganado popularidad por sus beneficios para el cabello y el medio ambiente. Este shampoo está elaborado con aceite de aguacate y vitamina E, dos ingredientes conocidos por sus propiedades hidratantes y reparadoras. Es ideal para cabellos muy secos y teñidos.', 120, 'AguacateTiendaBC.jpg', '80 gr'),
    ('Shampoo de aloe 80 gr','Shampoo sólido','El shampoo sólido de aloe elaborado con aloe vera natural, vitamina E y aceite de coco, puede tener muchos beneficios para el cabello y el cuero cabelludo, y es ideal para el cabello graso. El aloe vera es conocido por sus propiedades hidratantes y su capacidad para aliviar la irritación del cuero cabelludo, mientras que la vitamina E es un poderoso antioxidante que puede ayudar a mantener la salud del cabello.',120,'AloeTiendaBC.jpg','80'),
    ('Shampoo de coco 40 gr', 'Shampoo sólido', 'El shampoo de coco sólido está diseñado para cabello normal o mixto y es elaborado con aceite de coco, aceite de oliva y vitamina E. Estos ingredientes proporcionan una limpieza suave pero efectiva al cabello, al mismo tiempo que lo hidratan y lo protegen.', 60, 'CocoTiendaBC.jpg', '40 gr'),
    ('Shampoo de carbón activado 40gr', 'Shampoo sólido', 'El shampoo sólido de carbón activado con aceite de ricino, aceite de coco, carbón activado y romero es una fórmula innovadora que combina los beneficios de varios ingredientes naturales para proporcionar una limpieza profunda y efectiva al cabello normal o mixto.', 60, 'CarbonTiendaBC.jpg', '40 gr'),
    ('Shampoo de chocoalmendras 40 gr', 'Shampoo sólido', 'El shampoo de chocoalmendras es una opción para combatir el cabello seco y para evitar el frizz en cabello. Este shampoo está elaborado con manteca de cacao, aceite de almendras y vitamina E, tres ingredientes naturales que proporcionan una hidratación profunda al cabello, al mismo tiempo que lo nutren y protegen de los efectos dañinos del medio ambiente y los procesos químicos.', 60, 'ChocoAlmTiendaBC.jpg', '40 gr'),
    ('Shampoo de trigo 40 gr', 'Shampoo sólido', 'El shampoo sólido de trigo para cabello seco es una opción natural y efectiva para hidratar y nutrir el cabello seco. Este shampoo sólido está elaborado con aceite de trigo y vitamina E, dos ingredientes que proporcionan una hidratación profunda al cabello, ayudando a restaurar su suavidad y brillo natural.', 60, 'FibraTiendaBC.jpg', '40 gr'),
    ('Shampoo de aguacate 40 gr', 'Shampoo sólido', 'El shampoo sólido de aguacate es un producto de cuidado capilar natural y ecológico que ha ganado popularidad por sus beneficios para el cabello y el medio ambiente. Este shampoo está elaborado con aceite de aguacate y vitamina E, dos ingredientes conocidos por sus propiedades hidratantes y reparadoras. Es ideal para cabellos muy secos y teñidos.', 60, 'AguacateTiendaBC.jpg', '40 gr'),
    ('Acondicionador 60 gr', 'Acondicionador', 'Este acondicionador sólido está hecho con manteca de cacao y karité, dos ingredientes que proporcionan una hidratación profunda y duradera al cabello. Además, contiene vitamina E, un antioxidante natural que ayuda a proteger el cabello de los daños ambientales y a prevenir la rotura y el debilitamiento del cabello. Es ideal para todo tipo de cabello.', 120, 'Acondicionador.jpg', '60 gr'),
    ('Shampoo de mascotas 40gr', 'Shampoo sólido', 'El shampoo sólido para mascotas elaborado con neem y moringa es una alternativa natural y ecológica para el baño de nuestras mascotas. Está hecho a partir del neem, que es una planta con propiedades antibacterianas y repelentes. Por su parte, la moringa es rica en antioxidantes y nutrienes que promueven la salud del pelo y piel de las mascotas.', 60, 'MascotaCuadrado.jpg', '40 gr'),
    ('Shampoo de mascotas 20 gr','Shampoo sólido','El shampoo sólido para mascotas elaborado con neem y moringa es una alternativa natural y ecológica para el baño de nuestras mascotas. Está hecho a partir del neem, que es una planta con propiedades antibacterianas y repelentes. Por su parte, la moringa es rica en antioxidantes y nutrienes que promueven la salud del pelo y piel de las mascotas.',30,'MascotaPatitaHueso.jpg','20 gr'),
    ('Esponja estrella','Accesorio','La esponja corporal elaborada con ixtle, la fibra del agave, es una opción ecológica y natural para el cuidado de la piel. Esta esponja es suave y no irrita la piel, por lo que es ideal para pieles sensibles y para su uso diario en la ducha o el baño. Además, al ser una fibra natural, no contiene productos químicos ni sintéticos, lo que la hace amigable con el medio ambiente.',70,'Esponja.jpg','N/A'),
    ('Portashampoo','Accesorio','Nuestros portashampoos son los compañeros ideales para tus shampoos y acondicionadores Kukui MID, ya que ayudan a conservarlos de mejor manera, haciendo que duren más. Están elaborados a mano y hechos con madera reciclada.',40,'Portashampoo.jpg','N/A'),
    ('Bolsita de tela','Accesorio','Esta bolsa ayudará a que puedas llevar tus productos Kukui MID de una forma práctica y sin generar residuos.',20,'Bolsita.jpg','N/A');